### ISSUE TITLE
Somehow decompilers are being duplicated every update

### ISSUE THREAD

**Issue by CouleeApps** [decompiler-explorer/decompiler-explorer#126]
See decompiler list in the admin backend: 
![image](https://github.com/decompiler-explorer/decompiler-explorer/assets/711973/45e27ee4-b92f-4e5f-aca1-47384c6b582e)

**Comment by CouleeApps** [comment]
And sometimes two of them are active at once?
![image](https://github.com/decompiler-explorer/decompiler-explorer/assets/711973/505f48a8-5d7f-45ac-8616-7057637d7ad8)

**Comment by negasora** [comment]
Fixed in 836cb7d6ed6d444e9878c8965dc815647f86eb6c - they weren't searching through all pages of a paginated response when trying to find if they can reuse an id. There should be a database constraint making sure this can't happen but we need to manually clean things up before we can apply that.
