### ISSUE TITLE
Angr takes an unreasonably long time for this case in prod?

### ISSUE THREAD

**Issue by CouleeApps** [decompiler-explorer/decompiler-explorer#13]
Basic "hello world" program that runs in 3 seconds on my local box, timed out on the deployment after 120 sec.

This binary: https://dogbolt.org/?id=a539678b-ea84-4dbd-9fbf-b566613f787

Upload: [uploads_binaries_797ff3689d304e6a9ffa154ee3e8e20d5d10b62e233740a6028dd0e03caaf3bf.zip](https://github.com/Vector35/decompiler-explorer/files/8567973/uploads_binaries_797ff3689d304e6a9ffa154ee3e8e20d5d10b62e233740a6028dd0e03caaf3bf.zip)

**Comment by CouleeApps** [comment]
... cleaned up the decompilations and restarted the workers and this no longer happens?

**Comment by psifertex** [comment]
Still happens on local builds but the major issue seems fixed. Current timeouts expected to improve with #48
