### ISSUE TITLE
server is unavailable

### ISSUE THREAD

**Issue by backtd** [decompiler-explorer/decompiler-explorer#145]
I tried rebuilding multiple times but it always breaks down and gives a 404 error because there is no entryfile.sh

``[FATAL tini (7)] exec ./entrypoint.sh failed: No such file or directory``

And it just spam creates containers until I stop the stack because they all exit and fail

Also running ``pipenv run python manage.py runserver 0.0.0.0:8000`` gives Server Error 500

**Comment by backtd** [comment]
Well I fixed it by changing the entrypoint.sh files (There is two) from CRLF to LF and changing the bash header on both to ``#!/usr/bin/env sh``

**Comment by backtd** [comment]
Welp seems like the 404 page not found still persists

**Comment by CouleeApps** [comment]
How are you trying to run this? There are build/run instructions in the readme for local deployment, which should just be using standard Docker images. Also, none of the shell scripts use CRLF. You might be having issues with Windows and git's autocrlf?

**Comment by backtd** [comment]
I ran it on a linux system same issues, I followed the steps to the exact but no matter what I do something always is wrong, for example my lastest issue is postgres password is never initialized and I have to manually set it although I did init the system

**Comment by backtd** [comment]
Right now there is no errors an all is running but no files are served, always 404 page not found

``2024-01-20 06:03:39 172.18.0.1 - - [20/Jan/2024:03:03:39 +0000] "GET / HTTP/2.0" 404 19 "-" "-" 9 "-" "-" 0ms``

**Comment by backtd** [comment]
I got everything running and working but one thing that keeps happening is this on the explorer

``PermissionError: [Errno 13] Permission denied: '/opt/decompiler_explorer/staticfiles/favicon.ico'``

**Comment by backtd** [comment]
I fixed the permission error by keeping it running on root but now the container runs gives this message ``System check identified no issues (0 silenced).`` then exits and a new one starts I just dont know what to do at this point

**Comment by backtd** [comment]
Was able to solve that issue, I simply reverted back some content to its origin in docker and did a rebuild and all looks good but here is what the explorer is stuck on

```
System check identified no issues (0 silenced).
[2024-01-20 17:34:30 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2024-01-20 17:34:30 +0000] [7] [INFO] Listening at: http://0.0.0.0:8000 (7)
[2024-01-20 17:34:30 +0000] [7] [INFO] Using worker: sync
[2024-01-20 17:34:30 +0000] [27] [INFO] Booting worker with pid: 27
[2024-01-20 17:34:30 +0000] [28] [INFO] Booting worker with pid: 28
[2024-01-20 17:34:30 +0000] [29] [INFO] Booting worker with pid: 29
[2024-01-20 17:34:30 +0000] [30] [INFO] Booting worker with pid: 30
```

And the other containers logs server is unavailable
