### ISSUE TITLE
Run output through `rustfilt`?

### ISSUE THREAD

**Issue by aytey** [decompiler-explorer/decompiler-explorer#157]
I have no idea if this is a "back-end" tool problem or a "front-end" presentation problem.

I guess Question #1: if you decompile C++, who is responsible for showing the unmangled names? The tool or the front-end? Is there any precedence to put `c++filt` between the tool output and the front-end?

Then on to my (real) question: I am using dogbolt to look out the output of some simple Rust binaries, but these contain the "mangled" name (e.g., `_RNvCs3D4dQeFb3sN_4rust5quack`); running these through `rustfilt` gives something like: `rust::quack`. Seeing the unmangled names is really a lot easier to make the output understandable.

**Is this something dogbolt could support, or do I need to get all tool authors to support them running `rustfilt` over the output?**

Ghidra does actually give the unmangled name, which makes me think this is a tool bug and not a front-end bug.

The following tools:

 * BinaryNinja, dewolf, RecStudio, Relyze and RetDec 

all generate the mangled name (i.e., `_RNvCs3D4dQeFb3sN_4rust5quack`), so I can manually run the output through `rustfilt` if I wanted.

However, Hex-Rays actually generates a "corrupted" form of the name: it generates `RNvCs3D4dQeFb3sN_4rust5quack`, omitting the leading underscore, which then doesn't work with `rustfilt`.

**Full disclosure**: I have zero issue if this issue gets closed as "tool vendor problem".

**Comment by negasora** [comment]
Yeah this is a request that should go to each tool author. We want to show each tool's output as-is so it's a fair comparison.

**Comment by negasora** [comment]
Unsure about other tools but binja issues/feedback can be opened at https://github.com/Vector35/binaryninja-api

**Comment by aytey** [comment]
> Unsure about other tools but binja issues/feedback can be opened at https://github.com/Vector35/binaryninja-api

Awesome.

I requested that here: https://github.com/Vector35/binaryninja-api/issues/5218
