### ISSUE TITLE
as an author i would like to access a binary i uploaded

### ISSUE THREAD

**Issue by Yoshimitsuokita** [decompiler-explorer/decompiler-explorer#166]
i would like the snowman version of the source code of binary named TIbia. I uploaded this today.

**Comment by fuzyll** [comment]
We're a community project and not really in the business of figuring out how to copy/paste output to people, sorry. When you uploaded the file, you should have had a permalink you could use to retrieve the output from the website. I'd recommend using that to access what you need or setting up your own local copy from the source in this repo.

Also, reading into some more context from your other GitHub issues...if you're trying to port something from x86_64 to ARM this way, I wish you luck! But, this is a _very_ difficult process and not something you're likely to be able to do by just running a binary through a web app.

**Comment by Yoshimitsuokita** [comment]
How do you get the permalink

**Comment by fuzyll** [comment]
After you upload your file, you should be navigated to the URL `dogbolt.org/?id=<file_id>`. That's the permalink.

**Comment by Yoshimitsuokita** [comment]
The permalink will give me the file?

**Comment by fuzyll** [comment]
You provide a file. The decompiler explorer runs the selected decompilers on that file. The results are displayed in your browser, which can be copied from their respective text boxes. There are no files to download.

**Comment by Yoshimitsuokita** [comment]
When I try to copy from the browser I can't in the text box. Do I copy from the permalink you mentioned?

**Comment by Yoshimitsuokita** [comment]
Do you mean I have to type everything out?
