### ISSUE TITLE
i want the source code i uploaded but i cant find the permalink and im almost a 1000% sure its not there

### ISSUE THREAD

**Issue by Yoshimitsuokita** [decompiler-explorer/decompiler-explorer#167]
this is what this said

All submitted binaries are saved and made available to any of the authors of the tools used so they may improve their decompilers. If you're such an author who would like access, [let us know!](https://github.com/decompiler-explorer/decompiler-explorer/issues).

i really need the access thanks again

**Comment by negasora** [comment]
If you uploaded the binary then reupload it and you'll get the output.
Also that goes for tool authors, which I don't think you are?

**Comment by Yoshimitsuokita** [comment]
oh so that means i have to type it all out if i want it? im not a tool author. i just needed the source code file
