### ISSUE TITLE
Access to the binaries

### ISSUE THREAD

**Issue by aleclearmind** [decompiler-explorer/decompiler-explorer#173]
Ale from rev.ng here `:)'.

As discussed at REcon, it'd be nice if we could get access to the dogbolt binaries.

Let me know if you need an SSH public key or the like. Feel free to drop me an e-mail at ale@rev.ng.

I'd also like to get an idea of the update policies you have, we'd be really happy if rev.ng could get updated frequently `:)`.

**Comment by psifertex** [comment]
Handled in person. :-)

**Comment by psifertex** [comment]
Oh! RE: update policies right now we (V35) push updates whenever a stable is out for BN, IDA, and Ghidra, and others, but we can certainly update more frequently. Angr updates once per week typically.

**Comment by psifertex** [comment]
All that said, at whatever interval you want to, feel free to submit PRs.

**Comment by CouleeApps** [comment]
If you use git tags/github releases we can sub to the RSS feed and use that. Ideally I'd like to pin the docker buildfile to a specific version (right now it just curls master) but building all of llvm on the CI is a bit beyond our compute resources at the moment
