### ISSUE TITLE
Frontend should display disclaimer about binary retention policy

### ISSUE THREAD

**Issue by mborgerson** [decompiler-explorer/decompiler-explorer#18]
We want this service to help improve the tools, so when things fail we may collect and store the submitted binary for analysis. Don't send us anything you don't want us to keep.

**Comment by psifertex** [comment]
Done with https://github.com/decompiler-explorer/decompiler-explorer/commit/4d68414b717f09464c1fe4bb71e240db40f6b18e will be live shortly
