### ISSUE TITLE
Add `revng-c` decompiler

### ISSUE THREAD

**Issue by cher-nov** [decompiler-explorer/decompiler-explorer#184]
This is a recently emerged decompilation framework that has been open-sourced.

https://github.com/revng/revng-c - backend
https://news.ycombinator.com/item?id=39859000 - discussion on open-sourcing
https://rev.ng - official website

**Comment by cher-nov** [comment]
Oh, it's a duplicate of #155, which was resolved in decompiler-explorer/decompiler-explorer@7682659922000773850809870826059229618700. Sorry then.

**Comment by psifertex** [comment]
Heh, was about to say, it's already live!
