### ISSUE TITLE
Need FAQ Page

### ISSUE THREAD

**Issue by fuzyll** [decompiler-explorer/decompiler-explorer#2]
We need an FAQ page that includes:

- [x] What this is (for people who aren't familiar with decompilers)
- [x] Links and short descriptions for all of the tools involved
- [x] How it's being hosted (CPUs, RAM, etc)
- [x] Who made it
- [x] Where to get the code
- [x] How to contribute to the code

Anything else?

**Comment by psifertex** [comment]
Few more details added in an upcoming commit, considering this done.
