### ISSUE TITLE
Need Logo/Branding

### ISSUE THREAD

**Issue by fuzyll** [decompiler-explorer/decompiler-explorer#3]
We need a little logo and some simple branding stuff (theme colors, font, etc).

**Comment by psifertex** [comment]
Possibilities:

<img width="599" alt="decompiler-explorer-d" src="https://user-images.githubusercontent.com/140215/165420364-48716375-903c-4502-80e0-ea5089a6882e.png">
<img width="741" alt="decompiler-explorer" src="https://user-images.githubusercontent.com/140215/165420366-0ece99fb-3bf4-4319-9bd9-6cfd1fc9da61.png">
<img width="610" alt="dogbolt-chosen" src="https://user-images.githubusercontent.com/140215/165420401-eecb830a-744b-4333-939b-a29bf08c49f2.png">
<img width="502" alt="dogbolt" src="https://user-images.githubusercontent.com/140215/165420403-80d6dbc0-3c2c-4969-853c-034f6514bdd2.png">

**Comment by psifertex** [comment]
Went with hero dog for now. Closing, can re-visit later.
