### ISSUE TITLE
Service redeployment causes availability disruption

### ISSUE THREAD

**Issue by mborgerson** [decompiler-explorer/decompiler-explorer#32]
When we merge a fix, the entire site goes down apparently. It would be nice to minimize this disruption. An easy solution is to have the public service update nightly. Ideally standing up the new version before tearing the old version down so we can transition smoothly.

**Comment by negasora** [comment]
This is fixed by `a1eb9540a81440a963af56537f07f35e0249a2d3` through `f0912b087e37060661f0cbb8c523013dd3312769`
