### ISSUE TITLE
Boomerang, Reko, Snowman hung?

### ISSUE THREAD

**Issue by mborgerson** [decompiler-explorer/decompiler-explorer#37]
I'm not familiar with Boomerang, but Reko and Snowman should be pretty fast. Something may be broken in the backend.

**Comment by CouleeApps** [comment]
Fixed by [6ea92f1](https://github.com/decompiler-explorer/decompiler-explorer/commit/6ea92f11181e65b6eb01bfd6a6ebf52834907efb)
