### ISSUE TITLE
Some provided samples show analysis timeouts

### ISSUE THREAD

**Issue by mborgerson** [decompiler-explorer/decompiler-explorer#55]
Some of the provided samples include binaries which apparently timed out during analysis:
* Preferably we adjust the timeouts so this does not happen on samples, especially with default-enabled tools.
* Sample binaries are not available so I cannot confirm locally and check that the tool is not choking on the input.
* The timeout is not listed so I don't know how long the tool took before timing out.

![Screenshot from 2022-07-14 16-29-38](https://user-images.githubusercontent.com/8210/179118006-368f4041-31fe-43f8-ad0d-d85fce9d4e80.png)

**Comment by CouleeApps** [comment]
These have been re-run but one of the angr runs still timed out. Disabling timeouts on samples is an interesting question of performance reporting, and I'm not sure about it.

**Comment by negasora** [comment]
> Preferably we adjust the timeouts so this does not happen on samples, especially with default-enabled tools.

We should probably choose sample binaries that don't time out

> Sample binaries are not available so I cannot confirm locally and check that the tool is not choking on the input.

Tracked by #63 

>The timeout is not listed so I don't know how long the tool took before timing out.

Fair, I think it should be in the faq

**Comment by CouleeApps** [comment]
Addressed in https://github.com/decompiler-explorer/decompiler-explorer/commit/4319957858209702441303737884856170896681
