### ISSUE TITLE
Show analysis duration

### ISSUE THREAD

**Issue by mborgerson** [decompiler-explorer/decompiler-explorer#56]
It may be insightful to see how long an analysis took in a particular tool.

Related #55

**Comment by negasora** [comment]
Without running on the same hardware with the same load idk if the numbers would be honest enough to share. We had this before, but scrapped it because how finicky it was to keep conditions the same

**Comment by mborgerson** [comment]
Analyses should generally be executed under similar conditions, and we can give a disclaimer of it not being a perfectly accurate benchmark of tool performance based on service demand/conditions. My thoughts are something similar to how GitHub actions shows how long a task took in terms of seconds, not microseconds.

**Comment by CouleeApps** [comment]
This is blocked on #45

**Comment by CouleeApps** [comment]
This has been a feature for almost two years now. It's in the tooltip text for the decompiler version (not prominently displayed because it's not very precise due to server noise, also because ghidra takes forever)
