### ISSUE TITLE
Embedded Javascript causes errors

### ISSUE THREAD

**Issue by mborgerson** [decompiler-explorer/decompiler-explorer#61]
Uncaught ReferenceError: hljs is not defined
https://github.com/decompiler-explorer/decompiler-explorer/blob/b9c8df7a6f5a81d19d7b6b63df414a6a1b47981d/templates/explorer/index.html#L129

Looks like old highlighting code and probably just needs to be pulled out.

**Comment by negasora** [comment]
Fixed by 1151e06c8a5b88ffc528146c5a60d2f81bedb244
