### ISSUE TITLE
Adjustable timeouts

### ISSUE THREAD

**Issue by agentzappo** [decompiler-explorer/decompiler-explorer#70]
Providing an easy means of adjusting the timeouts would allow users to analyze binaries that do not complete in the fixed 120s window. Maybe my server is slower than everyone else's, but i'm running into some examples on my deployment where the decompilation does not complete within the provided time.

**Comment by psifertex** [comment]
Which timeout are you specifically referring to? There's a bunch in Analysis/Limits already, is there one that should be there but isn't? 
![Screen Shot 2022-07-20 at 8 28 07 AM](https://user-images.githubusercontent.com/140215/179981865-07024d0a-004f-428a-8240-4f60a058a41a.png)

**Comment by agentzappo** [comment]
Oh yeah I saw that I can adjust the timeout manually and re-deploy. My suggestion is for the timeout value to be adjustable after deployment (without requiring source mods). I get the motive for the public instance, but elsewhere it would be helpful to quickly allow users to re-analyze when their submissions don’t complete on-time.
