### ISSUE TITLE
Feature proposal: Periodically re-decompile example binaries

### ISSUE THREAD

**Issue by ltfish** [decompiler-explorer/decompiler-explorer#74]
We probably want to re-decompile example binaries when each decompiler releases a new version, or when a new decompiler is added to the party.

**Comment by CouleeApps** [comment]
This is happening pretty regularly now. I made a script locally which does it, but it would not be difficult to add to the CI. I just manually run it whenever I update the decompilers, which should be often enough because they don't change versions in between :)
