### ISSUE TITLE
Access to Samples

### ISSUE THREAD

**Issue by steffenenders** [decompiler-explorer/decompiler-explorer#83]
Hi!
I am one of the researchers working on the dewolf decompiler (https://github.com/fkie-cad/dewolf).
We would love to have access to both the uploaded samples and the example files you provide on Dogbolt to further improve dewolf's stability - would that be possible?

**Comment by psifertex** [comment]
Certainly! Shoot me an email (in my profile) and I will get you set up. Let us know if there's anything we can do to tweak how we are launching dewolf as well.

**Comment by psifertex** [comment]
Resolved via email.
