### ISSUE TITLE
python decompiler explorer: compare uncompyle6 pycdc decompile3 unpyc37-3.10 ...

### ISSUE THREAD

**Issue by milahu** [decompiler-explorer/decompiler-explorer#86]
provide a decompiler-explorer for python decompilers

- https://github.com/rocky/python-uncompyle6 for [python 3.8](https://github.com/rocky/python-uncompyle6/issues/331) and below 
- https://github.com/zrax/pycdc for all python versions
- https://github.com/rocky/python-decompile3 for python 3.7 to 3.8
- https://github.com/greyblue9/unpyc37-3.10 for python 3.7 to 3.10
   - Mostly complete support for Python 3.9
   - Minimal support for Python 3.10

binary python packages have only binary *.pyc files

bonus points for adding python compilers
so users can see original source versus decompiled source

**Comment by psifertex** [comment]
Unfortunately this is not in-scope for dogbolt at this time, but you're welcome to fork your own version for that purpose.
