### ISSUE TITLE
Add Samples

### ISSUE THREAD

**Issue by CouleeApps** [decompiler-explorer/decompiler-explorer#9]
It would be nice to have sample files included on the site to demonstrate the functionality without requiring users to upload a binary of their own. It would make using the site from a phone actually have results. Also it would demonstrate the output for desktop users who initially open the site, instead of just a blank screen.

**Comment by CouleeApps** [comment]
Implementation for this is done. All we need now is the content.

**Comment by psifertex** [comment]
Many samples were selected for now. Can update going forward as well. See #46
