### ISSUE TITLE
upload file size?

### ISSUE THREAD

**Issue by Bizarrus** [decompiler-explorer/decompiler-explorer#97]
How i can change the maximum of uploading file size up to `5 MB`?

Its possible to change this on the demo page to `3 MB`?

**Comment by negasora** [comment]
You can run with the env var `MAX_REQUEST_SIZE` set to a higher value
See: https://github.com/decompiler-explorer/decompiler-explorer/blob/25a5c7884658b5749ef3fafbd856e39b36157da6/docker-compose.yml#L60

There aren't any plans to increase the limit on the public instance.
